# Dockerfile.deployer
FROM ghcr.io/foundry-rs/foundry:latest

USER root
# Install netcat
RUN apt-get update &&\
    apt-get install -y --no-install-recommends python3 curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && \
    apt-get install -y nodejs && \
    node -v && npm -v && npx -v && \
    rm -rf /var/lib/apt/lists/*

# Copy deploy script and verifier keys into the image
COPY tests/docker/deploy.sh /deploy.sh
COPY config/resultsverifier_vkey.sol config/statetransition_vkey.sol /opt/davinci/config/
RUN chmod +x /deploy.sh

WORKDIR /
EXPOSE 8000

# 1) run the deploy script (which writes /addresses.json)
# 2) then serve it forever on TCP port 8000
ENTRYPOINT [ "sh", "-c", "\
    /deploy.sh && \
    python3 -m http.server 8000 --bind 0.0.0.0 --directory /" ]
